import React, { useState, useEffect, SyntheticEvent } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
//import styles from "../styles/Home.module.css";

// React Icons
import { BsFillSunFill, BsGithub } from "react-icons/bs";
import { BiMenu, BiGlobe, BiMoon } from "react-icons/bi";
import { VscGlobe } from "react-icons/vsc";

// Utils function imports
import { addFetchBookmarks } from "../utils/databaseAPI";

// Interfaces

// Components
import Clock from "../components/Clock";
import ContentList from "../components/content/ContentList";
import DaisyModal from "../components/daisyUI/DaisyModal";
import DaisyJSXCollapse from '../components/inactive/DaisyJSXCollapse'
import DaisyCollapse from "../components/daisyUI/DaisyCollapse";

const Home: NextPage = () => {
  const [loading, setLoading] = useState(true);

  // Basic app-mounting logic:
  useEffect(() => {
    setLoading(false);
  }, []);

  if (loading)
    return (
      <div>
        <h2>Loading...</h2>
      </div>
    );

  return (
    <div>
      <Head>
        <title>Personal Web Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="headerLight">
        <figure>☆</figure>
        <h1 className="font-autobus text-2xl">App Title or Greeting</h1>
        <figure>
          <BiMenu />
        </figure>
      </header>

      <main className="container mx-auto overflow-hidden md:max-w-7xl">
        <section className="bg-gray-300 flex justify-center">
          <Clock />
        </section>
        <section className=" bg-gray-500 flex justify-center">
          <ContentList />
        </section>
        {/* <section>
          <DaisyModal />
          <DaisyCollapse />
        </section> */}
        <section>
          {/* <p>
            The Star Trek canon includes the Original Series, nine spin-off
            television series, and a film franchise; further adaptations also
            exist in several media. After the conclusion of the Original Series,
            the adventures of its characters continued in the 22-episode Star
            Trek: The Animated Series and six feature films. A television
            revival beginning in the 1980s saw three sequel series and a
            prequel: Star Trek: The Next Generation, following the crew of a new
            starship Enterprise a century after the original series;
          </p> */}
        </section>
      </main>

      <footer className="footerDiv">
        <p>github link</p>
        <BsGithub />
      </footer>
    </div>
  );
};

export default Home;
